name: CI

on:
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Run unit tests
      run: |
        echo "Cloning submodule"
        git submodule init
        git submodule update
        echo "Starting bats unit tests"
        ./run_tests.sh
